def run_exception():
    raise Exception('error...')

run_exception()